package leetcode.text_editor;

import java.util.ArrayList;
import java.util.List;

public class Solution {
    public static String[] solve(String[][] queries) {
        List<String> result = new ArrayList<>();

        TextEditor editor = new TextEditor();

        for (int i = 0; i < queries.length; i++) {
            // System.out.println("Action: " + queries[i][0] + ": " + queries[i][1]);
            switch (queries[i][0]) {
                case "APPEND":
                    editor.append(queries[i][1]);
                    break;
                case "MOVE":
                    editor.move(Integer.valueOf(queries[i][1]));
                    break;
                case "FORWARD_DELETE":
                    editor.forwardDelete();
                    break;
                case "SELECT":
                    editor.select(Integer.valueOf(queries[i][1]), Integer.valueOf(queries[i][2]));
                    break;
                case "COPY":
                    editor.copy();
                    break;
                case "PASTE":
                    editor.paste();
                    break;
                case "UNDO":
                    editor.undo();
                    break;
                case "REDO":
                    editor.redo();
                    break;
            }
            result.add(editor.getContent());
            editor.printContent();
        }

        return result.toArray(new String[result.size()]);
    }

    public static void main(String[] args) {
        String[][] actions = {{"APPEND","Text generated by AI."},
                             {"MOVE","20"},
                             {"FORWARD_DELETE"},
                             {"APPEND"," that will conquer the world!"},
                             {"APPEND","!!"},
                             {"UNDO"},
                             {"APPEND"," Stop it!"},
                             {"UNDO"},
                             {"UNDO"}};
        Solution.solve(actions);

        /*
            ["Text generated by AI.",
             "Text generated by AI.",
             "Text generated by AI",
             "Text generated by AI that will conquer the world!",
             "Text generated by AI that will conquer the world!!!",
             "Text generated by AI that will conquer the world!",
             "Text generated by AI that will conquer the world! Stop it!",
             "Text generated by AI that will conquer the world!",
             "Text generated by AI"]
         */
    }
}
